### ISSUE TITLE
MacOS High Sierra 

### ISSUE THREAD

**Issue by djkinetic** [steveschow/gfxCardStatus#20]
Just a heads up 2.4.3i currently still working on the first dev beta of 10.13 this is on my mid 2012 retina 15 MacBook Pro.

**Comment by steveschow** [comment]
Thanks for that feedback!

**Comment by Taco55** [comment]
Unfortunately, this is not the case for my mid 2010 Macbook Pro 15 inch.
Although I am able to select the integrated only option, it appears that it does not become in effect. I.e. the icon does not change to "i" and the system keeps crashing at least every 30 minutes as before without gfxCardStatus.
Could the longevity of the 2010 Macbooks still be prolonged? Or has the time come to abandon this type forever?

**Comment by steveschow** [comment]
Check out the other thread, some people have figured out how to hack the efi firmware to hide the nvidia card from OS X.  This might be the best long term solution but I'm afraid to try it.  If you're ready to throw away the mbp then it's worth a try.  I'm staying on el cap for the time being.

Just out of curiosity did you clean install high sierra or upgrade?   Gfxcardstatus might be struggling due to something that is running at startup and turning on nvidia before Gfx can stop it

**Comment by cfettah** [comment]
Thanks for that feedback!

**Comment by Taco55** [comment]
I both tried an upgrade and clean install of high sierra, but GfxCardstatus was unable to disable the discrete card (without warnings). However, with another great solution that was created for this specific laptop it did solve the gpu problem!! See [MBPMid2010_GPUFix](https://github.com/julian-poidevin/MBPMid2010_GPUFix).

So I am happy that this laptop may survive for some more time...
Thanks for your help!

**Comment by steveschow** [comment]
Thanks for letting us know about that!  I presume it's basically disabling the nvidia card entirely by hacking the power management kext.  Please let us know if you have any problems with it.  Test out sleep and other power management features!  

The downside of this app is that it will need to be kept up to date with all future OS X updates.  Every time apple updates the power management kext then this utility also has to be updated with a new release, potentially.  Does look to be more reliable then gfx though presuming OS X does not cough and sputter sometime when it thinks it must have an nvidia card, such as for external monitor.  Try out Siri for example and let us know what happens.

That other thread has a link to another potential solution which looks to be more permanent but does not include a nice easy mac app to use it.  You basically have to create a Linux boot cd and then you boot the mac into Linux and manually change some codes in the EFI that essentially hides the nvidia from the computer at a more fundamental lower level.  After that you should not need a hacked kext nor gfxcardstatus.  And in fact you could run windows in boot camp without issues also.  I'm afraid to try it, but if your mbp is basically dead otherwise it would absolutely be worth a try.  I will try to repost those links on this thread later, it's on one of the other issues I posted it already.

**Comment by steveschow** [comment]
Taco55, I have created a dedicated ISSUE to provide alternative hacks such as the one you are now using.  Please check it out.  I posted yours already and another one.  Please let us know what works for you on that that issue thread.

[https://github.com/steveschow/gfxCardStatus/issues/21](url)

**Comment by maciboy** [comment]
Just installed 10.13 on my test-partition above an existing 10.12 installation…
Unfortunately I’m experiencing the same issue:
No dependencies, but MBP 2010 15“ just won’t switch to Intel graphics 😭

**Comment by maciboy** [comment]
Btw: @Taco55 please fill a bug report in Feedback-Assistant so Apple can notice that our MBPs are generally effected

**Comment by Chamiu** [comment]
Unfortunately, 2.4.3i and 2.4.4i do not change to iGPU from dGPU(AMD) on MacBook Pro Early 2011 15in.
macOS High Sierra Public Beta 1 upgrade from macOS Sierra.6 Public Beta 5.

Perhaps I think macOS bug, because do not work Time Machine and spotlight...

**Comment by maciboy** [comment]
With DP4 graphic switching is working again as intended :)
Nvidia card is not switched on by no reason 👍

**Comment by Chamiu** [comment]
me too !
