### ISSUE TITLE
Which version for primarily monitoring GPU switching?

### ISSUE THREAD

**Issue by JayBrown** [steveschow/gfxCardStatus#33]
I've previously used gfxCardStatus (still do) on my old MBP to keep it locked in integrated-only mode. Works great, thank you.

Now on my new MBP I just want to use gfxCardStatus as a monitoring app for GPU switching, and maybe occasionally switch to integrated-only, e.g. when on the road. But as the main setting, I'd like to keep it running the system-default Dynamic Switching.

So which version (or fork) should I use for that?

EDIT: currently on High Sierra (latest); will be on Mojave quickly.

**Comment by JayBrown** [comment]
OK, it seems that after testing it a couple of days, v2.4.3i is doing a fine monitoring-only job on High Sierra on a new MBP.

I do believe that this is a great little helper app: it's nice to know when the system switches to the dGPU, and which processes are responsible.

@steveschow : So my suggestion is, even though there won't be any more development on the app, that you should consider at least providing compatibility fixes for coming macOS upgrades, should problems arise. (?)

**Comment by steveschow** [comment]
Glad to hear it’s working for you.  No more development will happen on this fork.  You should check out the main line, owned by the original author of the tool for any new developments.  I only made this fork in order to fix a couple small things that he was unwilling to fix.  I am personally not using the tool any longer and there are many aspects about this code and OS X development in general that I don’t know much about.  So just being honest, I’m not going to spend any more time on it.  Someone else is more then welcome to continue carrying the torch from here.  But the mainline version of this app is more likely to be updated and if you’re only using it for monitoring then I think it will work fine.
