### ISSUE TITLE
With v2.4.2i and Sierra I get GPU panic under integrated only mode!

### ISSUE THREAD

**Issue by jimbojetlag** [steveschow/gfxCardStatus#9]
MacBook Pro mid 2010 here. Crashing under integrated mode never happened to me before.

You did not recommend v2.4.3i for mid 2010, so I tried v2.4.2i instead, and it crashed under integrated only mode.

**Comment by steveschow** [comment]
I'm not sure where you got the information about mid 2010.  I'm using a  mid 2010 with 2.4.3i and it works great.  Try that.  If it still crashes it may be related to a program you are trying to use that needs to be in discrete mode.

**Comment by jimbojetlag** [comment]
> I'm not sure where you got the information about mid 2010.

The release page:

![image](https://cloud.githubusercontent.com/assets/11205806/21247668/33ca4e20-c329-11e6-8779-f86cba0b6517.png)

https://github.com/steveschow/gfxCardStatus/releases

**Comment by steveschow** [comment]
Oh yea, its coming back to me now.  Can't do anything about it sorry.  There is something about our older MBP's from 2010 that supposedly doesn't work with sierra, I cant' remember the details right this minute.  I'm staying on El Capitan with my MBP actually, this is one reason why.  As to why 2.4.2 is crashing, what apps are you trying to run?

**Comment by jimbojetlag** [comment]
Nothing spacial really. Randomly crashing when browsing on Chrome. Note that it was forced to Integrated Only mode.

> There is something about our older MBP's from 2010 that supposedly doesn't work with sierra

I've installed v2.4.3i on Sierra, and it allowed me to choose Integrated Only. I'm not sure what the expected brhavior of this version on mid 2010 and Sierra is supposed to be.

**Comment by steveschow** [comment]
I can't remember now why I made that note, but I can tell you that I have been running 2.4.3i on El Capitan (2010 MBP) for quite some time without any problems, so if 2.4.3i works for you, count your blessings and use it.  Let me know how that goes.
Chrome attempts to do a lot of discrete graphics stuff, so if you're in integrated only mode, anything could happen, but this is the first I have heard of anyone getting a kernel panic in integrated-only mode

**Comment by jimbojetlag** [comment]
Reporting that 2.4.3i on Sierra 2010 MBP also crashes, **when in integrated only mode**!

Interesting part is that when visiting https://www.google.com/webdesigner/ by chrome, it causes GPU panic consistently.

The panic log clearly shows nvidia library traces. How can an nvidia GPU panic happen while being in integrated only mode? When visiting that web page, chrome must have used nvidia to render. The two graphic cards cannot be in use at the same time.

Is there a chance that while this patch shows integrated only in UI, it is actually using the discrete card?

No graphic card switching notification happens just before GPU panic.

**Comment by jimbojetlag** [comment]
![image](https://cloud.githubusercontent.com/assets/11205806/21265294/ada0e186-c398-11e6-8dd6-d7b8662cd45b.png)

I can see in Monitor that Chrome is marked as Required High Perf GPU, does that mean that it uses the discrete card even when gfxCardStatus is in integrated only mode?

**Comment by steveschow** [comment]
Could be, ask Cody.  I don't really understand that much about how the GPU switching works, this is really cody's baby not withstanding the fact that he seems uninterested in maintaining the code now.  The only thing I did on this fork is add some code to bring it back to integrated whenever the OS forces it to discrete when exiting apps.  

So when in integrated only mode whenever you quit an app you will see the menu switch momentarily to discrete and back to integrated again.  Without my patch it would change to discrete-only and remain there.

 Then later someone had some problems with sierra and tracked it down to a small bit of code which I removed for their sake and everyone seemed happy  This code would have always been skipped by 2010 macs anyway.

Is it possible that somehow chrome is switching to discrete without updating the menu?  I suppose so but you'll have to ask Cody and I doubt he will offer any help or info related to my fork so you will have to replicate the problem with 2.3 and ask him.

Sorry I can't be more help, honestly I just did this fork with the intention to avoid getting stuck in discrete-only mode.  The menu should be getting updated all the same as usual.  It's possible that chrome switches tobdiscrete and causes a kernel panic before the code has time to update the menu.

But the thing I am curious about is how chrome is able to force it to discrete at all when integrated-only is active, for any reason other then exiting the app.  The fact that is happening is something we need to figure out I guess or else our 2010 mbp's are going to become kernel panic junkware.  Sorry you're having this problem, if you come up with any specific information I am happy to hack on the patch to try to make it work.

I know people found that Siri on sierra needs to be disabled to avoid panic.  Could be some other things.  Apple forces discrete mode when trying to use an external monitor too for example.  There could be some other little feature the chrome is using which Apple forces to discrete, I really don't know.  Paradoxically Apple sometimes forces 2010 macs to discrete more then newer macs, i guess because they feel the integrated chip in our macs is less capable or something so certain open gl features get forced to discrete.  

My advise, avoid chrome and me personally I'm staying on El Capitan.  A few more years out of this laptop then I will buy a windows tablet, never getting another MBP personally.

**Comment by steveschow** [comment]
I find it interesting that it kernel panics at the same place in chrome every time.  To me this points the finger at Apple for having bugs in the code of either OS X or the GPU firmware or both; as opposed to being a case where the GPU has worn out, as has been implied for years.

**Comment by steveschow** [comment]
There is one more remote possibility which is that my integrated tweak is causing the kernel panic.  Please try running your chrome test while in dynamic switching mode to see if it still always panics at the same place.

**Comment by jimbojetlag** [comment]
> I find it interesting that it kernel panics at the same place in chrome every time. To me this points the finger at Apple for having bugs in the code of either OS X or the GPU firmware or both; as opposed to being a case where the GPU has worn out, as has been implied for years.

I do not understand why there is no lawsuit for this, Apple has clearly missold an expensive product to a large number of customers. It took them a few years to admit that the GPU units are defective, and then, they only offered a program which would replace the logic board on the condition that it passes their 'test'. Looks like their strategy it to offer too little too late, until these devices become old enough for the users to bother to do anything about it.

> There is one more remote possibility which is that my integrated tweak is causing the kernel panic. Please try running your chrome test while in dynamic switching mode to see if it still always panics at the same place.

I can confirm that when in dynamic switching mode, visiting https://www.google.com/webdesigner/ causes the GPU panic, consistently!

A few more observations:

- I uncheck 'use hardware acceleration when available' in Chrome and restarted it. Visiting https://www.google.com/webdesigner/ does not crash any more.
- After unchecking 'use hardware acceleration when available', Chrome shows a restart button. When clicking on that button, being in integrated mode, gfxCardStatus goes from **_i_** to  **_n_** to **_i_** icon.
- Surprisingly, unchecking 'use hardware acceleration when available' in Chrome makes it feel faster on 2010 MBP!

Thank you for your work on this fork. It is ridiculous that the community is trying to fix a mess caused by Apple, where Apple itself should be responsible for fixing.

**Comment by xmaenx** [comment]
@jimbojetlag , well try to install another app that will prevent google chrome from switching , I noticed that my VPN app (Private internet access) will maintain the integrated only try it even if you have no account just open it. I have the defected mid 2010 , and tried to open the link you provided and every thing is alright, I am now on Sierra and using the gfx v 2.4.3i

**Comment by xmaenx** [comment]
@jimbojetlag OK WAIT, I TRIED IT AGAIN TO OPEN THE LINK YOU PROVIDED AND MY COMPUTER CRASHED 👎  SO UNFORTUNATELY MY ABOVE ADVICE IS USELESS

**Comment by jimbojetlag** [comment]
Good to know that https://www.google.com/webdesigner/ crashes other laptops too. This could have been a good case against Apple if there was enough community traction.

Clearly in the light of this serious defect Apple should have recalled 2010 MBP, but in the absence of enough push from the community, they somehow got away from it.

**Comment by li-yuening** [comment]
MBP15 mid 2010
macOS Sierra 10.12.1
gfxCardStatus v2.4.2i (integrated mode)
Chrome 55.0.2883.95
Safari 10.0.1

@jimbojetlag My laptop either crashed when I was checking that Google page in integrated mode with Chrome with hardware acceleration on. I use this tool to prevent the discrete GPU from randomly crashing, and it works great before. Chrome also led to crashing when I quit gfxCardStatus and uncheck automatic switch in system Preferences to force using the discrete GPU.

Nothing happened using Safari, even with the discrete GPU in discrete  mode.

My laptop crashed more than 5 times when I tried to find some clues this morning, but all I got is:
1. this tool works great in 99% of time
2. stay away from Chrome :)

**Comment by jimbojetlag** [comment]
> stay away from Chrome :)

Like I said, unchecking 'use hardware acceleration when available' in Chrome and Firefox avoids that crash. Surprisingly, when **not** using hardware acceleration, Chrome runs faster under Sierra MBP15 2010.

Something is awfully wrong with MBP 2010.

**Comment by li-yuening** [comment]
@jimbojetlag My laptop crashed under Safari on that page with the discrete GPU in discrete mode after I opened it for a while this morning. It seems that Safari is not 100% safe. Right now I am looking at that page with Safari in integrated mode. So far so good.

Years ago, my laptop went through crashes and weird screen colors several times. I googled it and found there were few same complaints here in China. As far as I know, MBP 2011 with AMD GPUs has GPU defects and there is response from Apple. The 2010 model is too old now, and Apple just wanna let it be. Sigh :(

**Comment by steveschow** [comment]
Initially there was a response from Apple for 2010 mbp's a few years ago and they were replacing logic boards in them.  But I personally did not start having problems until I upgraded from snow leopard to mavericks.  Then suddenly I was getting panics.  But by then I was just barely past the 3 year AppleCare and Apple had ended the program to replace logic boards on 2010 mbp's.  I would think they will be ending it for 2011 soon, if not already.

But the thing is, people that have gotten the new logic boards have had the problem come right back again within months.

Bottom line is that the engineering on this series of laptops and/or how OS X operates with it pretty much just flopped.  They blew it and apparently knew nothing about how to fix it other then try to throw a bunch of expensive new logic boards at it for a while until they realized that wasn't really solving the problem either.  Now they are just hoping the problem will fade away with time.  But my 2010 MBP is pretty darn fast and capable.  I will be using it for quite a while yet.  As will many other people.  

I am curious if the MBP would have this problem running windows instead of OS X.  It would be interesting to find out if this is really a hardware problem or rather an OS problem.  Because of the fact that I suddenly started having this problem after upgrading several versions from 10.6 to 10.9.  But that could simply be the newer version is using more animation or transparency or other stuff and attempting to force the discrete video card more often, hard to say.

Anyway bottom line, Apple really let us down with these mbp's and some of the newer ones have the same problem too, so it's a long term issue that has apparently slipped through engineering for a while.  Apple definitely lost my confidence to buy another one.

**Comment by danielesposito** [comment]
Hi all.
I bought my MBP 2011 in mid May 2011. All was working well until I upgraded from Mavericks to Yosemite. Several days after the upgraded I got my first major crash/restarts/lock-up/screen stripes the whole lot. I ended up getting 4 logic board replacements done.
1 covered still under my extended warranty, 1 paid from my pocket, 1 replace for free from the place who replaced it the 2nd time and the last one I got it free of charge because I reached out to Apple and made my case.

After receiving my MPB from the 4th replacement, everything went smooth, thnx to gfxCardStatus. I also found that upgrading my OP system up to Le Capitan would result int the most stable system yet. I could even use my 2nd Monitor by running the HighEnd GPU. 

Doing Xcode etc, I ended upgrading to Sierra and that's where the nightmare started again.

It seems that the issue with these MBP 2011 could possibly be also OS X System related. 

I now started eliminating apps that run High End Graphics but still have 1 app that claims they don't need the High GPU, but Activity Monitor says otherwise. Every time I run this app, it would cause another crash/freeze the whole lot. In La Capitan I would run this app 8 to 10 hours a day without any issue. So, I do believe that Sierra on itself is a culprit. Maybe I will take the time and try downgrading again. I wished I had made a last final backup of my Drive before going to Sierra.

Anyways, wanted also to say Thanks for this gfxCardStatus app.

**Comment by NafetsPB** [comment]
@steveschow 

> I am curious if the MBP would have this problem running windows instead of OS X. It would be interesting to find out if this is really a hardware problem or rather an OS problem. 

Well, I have tried that. First I installed the "supported" version of Windows 7 Pro on my MacBook Pro mid-2010 using BootCamp. That seemed to work initially but I wasn't using that really, I almost instantly upgraded it to Windows 10 Pro. 

So, I am running Windows 10 Pro now from time to time. The upgrade install went fine but some applications show frequent crashes of the nVidia Display Driver, for example Google Chrome and Microsoft Visual Studio. Firefox, on the other hand, runs without problems.

Therefore both macOS (Sierra) and Windows 10 (Pro, 1607) do NOT work with the nVidia GPU enabled on a MacBook Pro mid-2010 when using an external display (Apple Cinema Display 27"). People running Linux on it report "no problems", though.

My guess is that there are certain "use cases" in both macOS and Windows that trigger this bug (a hardware issue, I suppose) whereas Linux does not.

These kernel panics started to appear on my system on El Capitan, especially after waking it from sleep with the notifications popping up. Since Sierra this is not even related to notifications or sleeping, it sometimes crashes out of the blue...

Since I am using an external display there is no way for me to get this "fixed"; the system refuses to drive the external display without the nVidia GPU so I guess it is time to buy a new system (most likely NOT a Mac) and use this MacBook Pro as a laptop only with the integrated GPU and not as a desktop replacement as I do now.

**Comment by steveschow** [comment]
Thanks for that report.  Under win10, does it blue screen the computer or just crash the app?  Just curious.  Does sound though like bugs in the nvidia firmware.

**Comment by NafetsPB** [comment]
@steveschow 

> Thanks for that report. Under win10, does it blue screen the computer or just crash the app? Just curious. Does sound though like bugs in the nvidia firmware.

There is NO blue screen under Windows 10 but a crash of the nVidia Display Driver (only). When this happens the screen goes completely blank for a second or two, then it shows up again and a Windows notification message pops up telling you about a crashed Display Driver. You can then resume your work until the next crash happens.

This is not as "dramatic" as the Kernel Panic that the same issue is causing on macOS but still the system - or rather the application(s) causing this - are not usable. When I start Google Chrome on Windows 10, for example, the nVidia Display Driver crashes constantly (every few seconds), rendering the system unusable. Once you quit the critical app, though, Windows can be used again whereas on macOS there is potential data loss due to the sudden Kernel Panics.

Interestingly, though, it seems to me (now) that these crashes are more frequent on macOS since I started using Google Chrome more than I used to. So it may be worth a try using Safari or Firefox again to see if the system is getting more stable...

**Comment by jimbojetlag** [comment]
> There is NO blue screen under Windows 10

Wow, never thought Microsoft and Apple would one day swap places.

I mean, Apple was clearly unable to fix its hardware engineering mess. The least they could do was to work on the software part to avoid a kernel panic. If Windows can do that,... why cannot unix?

**Comment by jimbojetlag** [comment]
> Interestingly, though, it seems to me (now) that these crashes are more frequent on macOS since I started using Google Chrome more than I used to.

Turn Chrome hardware acceleration off. It avoids the crash on Sierra.

**Comment by NafetsPB** [comment]
@jimbojetlag 

> Turn Chrome hardware acceleration off. It avoids the crash on Sierra.

I did that about two days ago after reading about that elsewhere. Let's see if this improves things. Nevertheless there are still many other apps/use cases that will potentially cause a macOS kernel panic besides Google Chrome, even though this seems to be causing issues on both macOS and Windows when it is using hardware acceleration.

> why cannot unix?

Well, it obviously can. At least some Linux users keep reporting "no issues" so it must be possible to somehow avoid a kernel panic - if Apple would invest some time and work.

However, recently it seems to me that Apple has lost a lot of interest in macOS and Mac hardware development so I do not think that there will ever be a fix from Apple regarding this issue.

**Comment by NafetsPB** [comment]
One more interesting note while I am at it:

My brother also had a mid-2010 MacBook Pro, most recently updated to El Capitan (not Sierra), and it was performing without any kernel panics for years.

Now he gave that MacBook Pro to our mother, and before doing so he did a fresh install of El Capitan. Since then, kernel panics started to appear quite regularly, on the exact same hardware.

The only difference that we could find is that he did not re-install gfxCardStatus that he was using before for many years. Coincidence?!

All of this makes we wonder if this can really be "just" a hardware issue that cannot be fixed...

**Comment by steveschow** [comment]
I personally think Apple could code around it if they wanted to but they don't want to and that has been their attitude for decades.  I also had no problems at all with snow leopard and then upgraded to mavericks and it started happening a lot with logIc pro x.  Obviously the newer versions of OS X are making full use of accelerated hardware and encountering the bug in the firmware somehow more often.  By Apple should know exactly what causes it and OS X should provide a path around it, especially since it often happens at a time when accelerated hardware isn't even really needed.  But I think it may have something to do with open gl in a way that would be too expensive to fix.

**Comment by maciboy** [comment]
> I know people found that Siri on sierra needs to be disabled to avoid 

With 10.12.4 Apple will bring changes to this: after ending interaction with Siri 'SiriNCService' gets quit properly (after approx. 1 minute) and GPU changes back to integrated 😃

**Comment by steveschow** [comment]
how are some of you faring with these problems since the latest Sierra update?  Just curious.  I'm still on El capitan and not planning to upgrade.  still problems with Chrome, etc?

**Comment by xmaenx** [comment]
I am now on version 10.12.4 (16E195)
And I can tell it is working perfectly fine, ALTHOUGH YOU HAVE TO AVOID COMPLETELY GOOGLE CHROME BROWSER.

**Comment by jimbojetlag** [comment]
> And I can tell it is working perfectly fine, ALTHOUGH YOU HAVE TO AVOID COMPLETELY GOOGLE CHROME BROWSER.

Well, I wouldn't call that 'perfectly fine'!

This is what worked for me: I disabled hardware acceleration in Chrome and Firefox. That's the only way to avoid the GPU panic on pages like https://www.google.com/webdesigner/ .

This has a couple of side effects:
1. When visiting bloated pages, the CPU fan starts making a lot of noise. That also includes playing youtube videos in fullscreen.
2. Some CSS3 (possibly 3D related) styles cause flickers on web pages that use them.

On the bright side, Apple laptops are no more the top choices for many people. This might not sound very positive to you, but I think this is what they deserve when they sell us defective hardware, and then they completely ignore it.

**Comment by li-yuening** [comment]
My Mac didn't get a kernel panic when I checked https://www.google.com/webdesigner in Chrome. I thought maybe macOS 10.12.4 has fixed it. But my Mac got a kernel panic when I checked http://www.imooc.com/article/6453 in Safari every time.
What about you guys?
Oh, forgot to tell, I didn't use gfxCardStatus.

**Comment by NafetsPB** [comment]
My MacBook Pro, recently updated to macOS 10.12.4, immediately ran into a kernel panic when I visited https://www.google.com/webdesigner using Chrome (directly after booting) and started scrolling the page. Then I tried  http://www.imooc.com/article/6453 in both Safari and Chrome: no panics. When I then opened https://www.google.com/webdesigner in Chrome again there was no kernel panic.

In my Chrome settings I disabled hardware acceleration but the MacBook Pro still insists on using discrete graphics whenever Chrome is running so I guess that this setting does not help or change anything (for me).

Thanks to these annoying kernel panics I now built myself a Hackintosh. It also runs macOS 10.12.4 and Chrome with hardware acceleration enabled. It never crashes. Thanks, Apple!
